### ISSUE TITLE
Moqui website typo

### ISSUE THREAD

**Issue by lektran** [moqui/moqui-framework#10]
Hi David,

There's a typo on your website in the Framework -> Home -> Introduction (True 3-Tier Architecture) section.

"role your own logic layer" should be "roll your own logic layer"

Regards
Scott

**Comment by jonesde** [comment]
Thanks Scott. I fixed this in the site repo (which is a private one) and will post it when I upload the next time.

**Comment by samhamilton** [comment]
Hey David, I also spotted a problem with the new site, so rather than open a new bug just commenting here. 

![screen shot 2016-02-04 at 11 41 28 am](https://cloud.githubusercontent.com/assets/415410/12805182/54d04464-cb34-11e5-8704-30c491d74a33.png)

As per the screenshot the header is not working quite as expected. 

Have you considered open sourcing the site, you never know you might get some pull requests?

**Comment by jonesde** [comment]
Which browser is that on?

The site is in a private repo because there are other sites hosted on the same server (all running through Moqui). I could pull just this directory into a site though... I'll think about that, it is a pain to maintain!

**Comment by samhamilton** [comment]
Pain is not good! 

Sorry about the lack of details, the first screenshot is from Chrome Version 48.0.2564.103 (64-bit)

This is Safari v9.0.3 (11601.4.4)
![screen shot 2016-02-04 at 11 59 22 am](https://cloud.githubusercontent.com/assets/415410/12805502/de17bd9a-cb36-11e5-9062-b35aa641001e.png)

This is Firefox v44.0
![screen shot 2016-02-04 at 12 02 05 pm](https://cloud.githubusercontent.com/assets/415410/12805536/27646bd8-cb37-11e5-8aef-4fbbaeef4b46.png)

All OS X 10.11.3

**Comment by lektran** [comment]
Forgot to mention: the new website looks great!

**Comment by jonesde** [comment]
Sam: Is that after scrolling down? If so then yes that is intended (there is space above the fixed menu bar).

**Comment by samhamilton** [comment]
Ah ok, I see
