### ISSUE TITLE
Current MoquiDefaultConf mySQL configuration unable to handle 4 byte characters.

### ISSUE THREAD

**Issue by ronankeane** [moqui/moqui-framework#104]
Can't see this issue raised before - in the current MoquiDefaultConf, mySQL implements 'UTF-8'. However, it is not full UTF-8. Only 3 byte characters are encompassed. 4 byte characters such as emojis from twitter  cannot be handled. The encoding required is utf8mb4, 'across the board'. (I had an issue with this but circumvented it with regex to strip out non-ASCII characters, so no urgency in my case.)

**Comment by jonesde** [comment]
What might we do about this at the framework level?

Databases are not simple things and there are many potential issues, and they vary with each database... some make sense to help out with in the framework to handle common cases and generally good practices, but I'm not sure this falls into that category. We can't predict or solve all issues with external software... and in this case I'm not sure it's even a good default to recommend because not all users need to support this (in fact I don't think it's all that common), and MySQL still does some funny things with multi-byte character sets and row size limits and such (though fortunately at least column widths are now in characters and not bytes! that was a huge headache).

**Comment by jonesde** [comment]
I suppose one improvement would be to add a comment about this in the sample configurations in MoquiDefaultConf.xml, is that what you had in mind?

**Comment by ronankeane** [comment]
Yes, that would suffice. I would not have detailed database knowledge, that is why I did not try to implement utf8mb4 myself, but rather circumnavigated the problem. And that was a simple and effective solution to the problem, compared to what seemed like a route that might possibly raise a host of other problems. In raising the issue I would certainly not be in a position to make a call on it, but I just thought I would raise it anyway.

**Comment by jonesde** [comment]
Notes added in commit #6410e6d.
