### ISSUE TITLE
Serious performance drawback with deployment in docker

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#120]
Same moqui-framework in different environments:

docker/simple with `java -cp . MoquiStart`
![image](https://cloud.githubusercontent.com/assets/4743845/18622038/7de6dca0-7e5d-11e6-94d3-af99fdda5efc.png)

In docker with tomcat
![image](https://cloud.githubusercontent.com/assets/4743845/18622001/e37e0134-7e5c-11e6-89e0-a22c70fbb1cc.png)

in tomcat 
![image](https://cloud.githubusercontent.com/assets/4743845/18621995/d275f694-7e5c-11e6-9f2c-34e1d032ec75.png)

run with `gradle run`
![image](https://cloud.githubusercontent.com/assets/4743845/18622065/d49dd8aa-7e5d-11e6-861c-75a74627c073.png)

I used 460da1b building moqui-framwork base docker images 11 days ago which run with tomcat, the test of "Render System Dashboard Screen" and "REST Client API get /basic/enums" both were around 150. 

All of them are run on my MacBook Pro with SSD and run 3 times to warm up cache.

**Comment by jonesde** [comment]
In my tests Docker ranged from 10-15% slower, though I don't know the exact reasons why. That was with a different sort of test, a load test from JMeter and running on Linux.

You have to watch Docker on the Mac... it runs in a weird way, basically a Linux virtual machine on OS X is the Docker Host machine, and then the Docker containers run in it. In other words, it has double virtualization. On top of this the Linux virtual machine running on OS X has resource limits, though I haven't dug into those much (seems to limit to a small percentage of system RAM, the Moqui instance only gets a heap size under 500MB on my Macbook Pro with 16GB RAM, running straight on OS X Java 8 defaults to giving it an 4GB max heap size). On my Linux workstation Docker containers seem to have access to all RAM, so even in Docker Moqui gets around 8GB (the Java 8 default of up to 1/4 RAM, and it has 32GB RAM).

The SpeedTest screen is an okay overall indicator, but you'll notice serious differences in times between runs when running all the tests because of garbage collection and such. With limited memory the system will spend a lot more time on garbage collection, and realistically for Moqui to preform at top speed it needs some memory for complex operations loads like this.

BTW, I usually run it quite a few more times than 3 when doing profiling and such to make sure the HotSpot compiler does its job... even hopping the run number up to 10,000 a time or two then going back to 1000 so there isn't so much GC delay during the tests.

Most importantly, and I should have mentioned this first, because of GC delays and such the best number to look at for overall performance is the time it takes ALL tests to run, not the time for an individual test as those will vary widely.

**Comment by shendepu** [comment]
I used the old docker image I made with 460da1b (runtime should be 81bafc2) 
![image](https://cloud.githubusercontent.com/assets/4743845/18622722/bab54830-7e65-11e6-9c09-fbeab12cf116.png)

but I used same commit 460da1b of moqui-framework and 81bafc2 of runtime and same docker file rebuild docker image and run it
![image](https://cloud.githubusercontent.com/assets/4743845/18622778/8fd3a322-7e66-11e6-9856-c161a9ec091d.png)

My MacBook pro is i7+16G. and of test run with same default heap size in moqui. 

Only difference on environment I guess is that 11 days ago the docker version I made the base image is different with the one on my Macbook now. It is 1.12.1-beta26.1, and 11 days agao it was beta 24 or 25. I recall upgraded it one or two times. 

I will run the docker on linux server to build it and see whether it is different or not.

**Comment by shendepu** [comment]
Build it on linux server is same slow. the dock version is 

    Docker version 1.12.1, build 6f9534c, experimental

Checked the system info by run two images on my Macbook, 
The old one which is fast (render dashboard, REST client API > 100) 
![image](https://cloud.githubusercontent.com/assets/4743845/18623444/b72d63c8-7e6f-11e6-95e7-aa3555e59b24.png)
slow one (Render system Dashboard screeen <4) 
![image](https://cloud.githubusercontent.com/assets/4743845/18623452/d105936a-7e6f-11e6-8a8e-2527473593c2.png)

In terms of performance difference, it is easy to notice rending page, access REST api in application as well. 

Don't know why. I don't have environment with docker <1.12 version to build image and test. I guess I have to use docker/simple to which using embedded jetty as the base image. But still especially REST client performance has 5 times difference (25.86 vs 123.78, figures from above snapshots)

**Comment by shendepu** [comment]
I use /docker/simple to build base image for moqui and mantle. I also used the pull request code https://github.com/moqui/moqui-framework/pull/121 since I need nginx proxy with ssl in front of embbed jetty. 

The performance is fine with application in production 
![image](https://cloud.githubusercontent.com/assets/4743845/18632051/fd0ddfac-7ea7-11e6-8d8a-ec010d21071e.png)
The `REST Client API get /basic/enums` got error may be caused by the docker environment which url base constructed in SpeedTest.xml is not https://my-domain. The Actual APIs run fine. 

So I think this issue can be closed.
