### ISSUE TITLE
(Possibly a question) Opening a content file in a new tab works, but application logs an error

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#124]
I have screen showing invoice. In the form I added a link pointing to a transition opening an attachment file:
![image](https://cloud.githubusercontent.com/assets/14863763/18914044/ab3139c8-858b-11e6-97c7-61f05da642da.png)

This is the transition itself:
![image](https://cloud.githubusercontent.com/assets/14863763/18914174/39ebe2ee-858c-11e6-965b-a318ccab4362.png)

And how it appears in the log:
![image](https://cloud.githubusercontent.com/assets/14863763/18913984/5e0bd8f6-858b-11e6-98f8-39f1d3c89c5b.png)

Both attachment open correctly. Is the transition to open an attachment (not downloading it) implemented incorrectly?

**Comment by jonesde** [comment]
You clipped the part of the log where it says which line it is on, but it may be the inline script near the end if invoiceContent is null.

**Comment by mrovnanik** [comment]
Sorry.

![image](https://cloud.githubusercontent.com/assets/14863763/18922659/d97f3c80-85a9-11e6-9f1e-a8b3bc835876.png)

**Comment by jonesde** [comment]
Yep, the stack trace shows it on line 15 of the script generated from the XML actions, which is logged above the stack trace, and it is blowing up because invoiceContent is null so it can't evaluate invoiceContent.contentLocation. Better to check for null invoiceContent (i.e. not found) and return an error message (ec.message.addError()).
