### ISSUE TITLE
When cache enabled, list view-entity with selectFields will return wrong results.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#14]
Have a view-entity using function, the group by clause will depend on selectFields.
The following line of code will add all fields, which return wrong results.
https://github.com/moqui/moqui-framework/blob/master/framework/src/main/groovy/org/moqui/impl/entity/EntityFindBase.groovy#L834

Because EntityCache not distinguish between selectFields difference. These type of view-entity should never cached. But If I enabled trasaction-cache, it will cache all entity event @cache="never".

**Comment by chunlinyao** [comment]
if the original fieldsToSelect has content, use cache will add all fields, and select duplicate fields. which waste bandwidth and cpu time.

**Comment by jonesde** [comment]
Caching view entities is always risky, there are warnings for certain scenarios when auto cache clearing won't work (like not all PKs aliased in the view-entity), but other potential scenarios where auto clearing won't work but it can't warn you about it.

Are you seeing a problem with the entity find cache, or the transaction cache? If it is the transaction cache see the notes at the top of TransactionCache.groovy... there are a bunch of scenarios that it doesn't handle. It handles quite a lot for what it does, but even in mantle-usl you'll see code blocks that check to see if the transaction cache is in place and if so it does a different sort of query, mostly because using view entities in general often has problems with the transaction cache. 

That is why it is not enabled for all code... you have to specify on a service when you want it to be used, and watch out for the issues with it (known and with comments, and perhaps unknown ones exist too). For some it might be possible to improve the transaction cache, in other cases the best solution is: change your code or don't use it!

**Comment by chunlinyao** [comment]
I saw this problem with transaction cache, but the entity find cache will have same problem, The only difference is with entity find cache, I can define @cahce="never" on the entity to workaround it. I have seen the code in mantle-usl, In that code, the view entity cannot work with transaction cache because the member-entity will change in same transaction. Member entities of my view-entity is read only in the service. EntityFindBase changed fieldsToSelect I passed in when transaction cache enabled, so group by clause changed. If the transaction cache also honor the @cache="never" attribute, transaction cache can work.

**Comment by jonesde** [comment]
That makes sense, and sounds like a good change to check cache=never before expanding the fields to select. Have you tried it yet and do you have a patch? If not I can do it, should be a pretty small change.

**Comment by chunlinyao** [comment]
I have't tried it yet.

**Comment by jonesde** [comment]
Looked into this more and the best solution is to cache a list in the tx cache only if there are no fields to select (i.e. all fields are selected). I made this change in commit #0bdf5dd, again in a forked repo right now because this code has changed a lot in recent cleanups and performance improvements that aren't merged yet.
