### ISSUE TITLE
Mantle USL Rest API - swagger throwing an error when showing Parties services

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#145]
I am using the latest code base (framework + runtime). The Mantle-UDM has not been updated, since I have my customization in it. When I attempt to open Mantle USL Rest API screen (for Parties), an error occurs. The others seem to work:

![image](https://cloud.githubusercontent.com/assets/14863763/20028975/2cf14d46-a340-11e6-9ceb-a82745c3a418.png)

![image](https://cloud.githubusercontent.com/assets/14863763/20028984/613fcf5a-a340-11e6-93d2-108a884b7382.png)

This is the error stack trace:

[ErrorStackTrace.txt](https://github.com/moqui/moqui-framework/files/573088/ErrorStackTrace.txt)

**Comment by mrovnanik** [comment]
The error is related to absence of partyId in the mantle.party.contact.ContactMechPurpose.

**Comment by jonesde** [comment]
It loads fine in the current code, ie the stock mantle.rest.xml file and the stock entity definitions. If you have changed those and something doesn't work there is probably an issue with your changes.

The question to look into is why is it looking for a partyId field (from a path parameter) on the ContactMechPurpose entity? It doesn't make any sense to have a partyId on that entity, so the issue is likely with a method.entity that has a partyId in the path but is looking at ContactMechPurpose.

**Comment by mrovnanik** [comment]
Yes, you are right. There must be something in my code.

But if you check your demo.moqui.org, there is an error which looks a bit similar to the one I encoutered:
![image](https://cloud.githubusercontent.com/assets/14863763/20034136/160905f0-a3b4-11e6-85e0-cb8e393f130b.png)
