### ISSUE TITLE
Issue when create/update WikiPage content 

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#148]
When create/update WikiPage, all the lines are merged into one.

I've checked and found that `pageText` param, which has `allow-html="safe"`, was changed by newly `Jsoup.clean` method in ParameterInfo.java

**Comment by jonesde** [comment]
As with all issues, please list steps to reproduce. Which wiki page type did you see this with, ie html, md, something else?

In my tests with HTML using Jsoup was actually a big improvement because it will format HTML as it cleans it, unlike the 2 previous libraries used that actually did have an issue of removing all extra white space, essentially putting all HTML on a single line, and because of this there used to be code in Moqui that did an additional step to at least put new lines before all opening tags (which was still ugly but better than one big line).

**Comment by locnguyenx** [comment]
I've just worked with current wikipage which uses md format

Steps to reproduce with demo.moqui.org:
- Open a wikipage (md): https://demo.moqui.org/apps/hm/wiki/DEMO/Demo+Page+1/Child+Page+1
- Edit page: may or may not change anything
- After update, all content becomes a single line

I also try create new html page and find that the cleaning is the same. However, this cleaning is normal for html.

**Comment by jonesde** [comment]
Thank you, I was able to reproduce this and it was being run through Jsoup.clean() because the text had encoding characters (% in this case) which should be allowed without needing cleaning with other types of text, ie non-html. Now it only cleans if there is a less than (<) character as of commit #641ee91.
