### ISSUE TITLE
Calendar dropdown picker is invalid under localized "zh"

### ISSUE THREAD

**Issue by hexd-moshi** [moqui/moqui-framework#154]
Calendar dropdown picker is invalid under localized "zh", but it is Ok under localized "zh_CN"

![image](https://cloud.githubusercontent.com/assets/22312976/20703509/e05681a2-b656-11e6-908d-34b03355fc3a.png)

**Comment by jonesde** [comment]
The calendar picker we use is a third party library, bootstrap-datetimepicker:

https://github.com/Eonasdan/bootstrap-datetimepicker

This uses Moment JS which has its own localization:

http://momentjs.com/

We pass a locale to bootstrap-datetimepicker, but beyond that it's up to those libraries to handle localization. In other words, it's not part of moqui-framework. If there is something different that needs to be done in Moqui we can do that (actually would be in moqui-runtime, not moqui-framework, in the DefaultScreenMacros.html.ftl file). Otherwise it's up to those third party libraries to handle that and it is best to work with those projects to handle things better.

If you find a change that works for you please submit a pull request. I won't close this for now in case other Moqui contributors want to work on this.

**Comment by hexd-moshi** [comment]
@jonesde , thanks for your quick response.
I will report this issue to bootstrap-datetimepicker, by the way, I will use "zh-CN" localized to cover it first.
Thanks!

**Comment by hexd-moshi** [comment]
I have reported it as below:
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1907

**Comment by jonesde** [comment]
I see he already responded, and it was a good response. Looking at the JS console in your browser before reporting any issue is a must for JS issues (just like console logs on the server are a must for issues that are server-side). It looks like this is an issue with Moment.js, or at least the version currently in Moqui. I would look there if you are still interested in pursuing this.

**Comment by jonesde** [comment]
This is an issue with Moment JS which defines localization for zh-cn and zh-hk but not plain 'zh' (which you can see in the moment-with-locales.min.js file). This is a minor issue and there is only so much we can do in Moqui about it, ie it would require a fair bit of work to review all of the Java locales versus the Moment JS locales supported and default to one in the JS code that Moment supports. I don't plan to do that so am closing this issue as there is a workaround.
