### ISSUE TITLE
how to create all tables when moqui start?

### ISSUE THREAD

**Issue by justin-wick** [moqui/moqui-framework#159]
i create an entity config in my own component, in dev mode, table always create when application use it, 
does it have a configuration let me see all tables when moqui start ?

**Comment by jonesde** [comment]
There is all sorts of great stuff in the documentation, including the solution to this with the datasource.@startup-add-missing attribute (set to true) in the Moqui Conf XML file. When doing this you should generally also set @runtime-add-missing to false.

This is done by default for some databases, like DB2, because it doesn't do well with table creation on the fly. See the database elements in the MoquiDefaultConf.xml file for details.
