### ISSUE TITLE
does moqui framework support lowercase sql

### ISSUE THREAD

**Issue by justin-wick** [moqui/moqui-framework#160]
i use moqui framework 2.0 , db is mysql,
my company specification, do not allow us use uppercase for table names and columns, does moqui support lowercase letter for table names and columns, like xxxx_moqui、user_acctount?

**Comment by jonesde** [comment]
Please provide more details: Which database are you using? Which errors are you seeing?

Changes could be made to default to lower case instead of upper case, but I have yet to use a database that doesn't handle this. The only issue I've seen is databases that return meta data in lower case even if it is created using upper case names (case insensitive, not case preserving) and there is code to handle that sort of thing.

**Comment by justin-wick** [comment]
we're using mysql database, 5.5.30, if i create table name like USER_ACCOUNT, when i excute select * from user_account , the database will return: [Err] 1146 - Table 'laowei.user_account' doesn't exist.

I do not have the authority to modify the database configuration, So I can only compromise in the framework of the configuration

**Comment by jonesde** [comment]
I and others have tested Moqui with MySQL quite a lot. Is that SQL run manually in the mysql console or an admin app, or run by Moqui? Perhaps you have the wrong schema name (same as database name in MySQL)?

**Comment by justin-wick** [comment]
thanks  for your testing,  Maybe I didn't describe it clearly. I apologize.In fact, this problem is not as complicated as you imagined.
i  create an app use moqui, and the default table name is uppercase , if we use moqui framework, it works fiine ,but if someone else want to use this table's data, and if he does not use moqui ,such like hibernate or mybatis or even jdbc, he use lowercase table name ,and got "Table 'xxxxx' doesn't exist." 
Based on this situation, i hope moqui has a configuration to change the default table names and columns so that they will not break company's code rules（like i said before , my company specification, do not allow us use uppercase for table names and columns）

**Comment by jonesde** [comment]
Moqui is not breaking anything... MySQL converts the names to all lower case and that's fine, it is case sensitive. A change to how Moqui creates tables would not fix anything. The error you are seeing is almost certain not related to upper or lower case, there is something else wrong. 

What I'm telling you is that the problem is in your other code or tools when they try to access the database, nothing in Moqui. You can verify this by using the mysql console or admin app to look at the tables and run test queries and such. With the meta data there write your Hibernate or other code to match.
