### ISSUE TITLE
how to change log level

### ISSUE THREAD

**Issue by justin-wick** [moqui/moqui-framework#164]
i am using moqiu frmework2.0 and runtime 2.0, i build framework with source code, i want to change log level outside,i copied log4j2.xml from moqiu-framework，but no matter which folder I put , it still not working,here is my project structure：
![image](https://cloud.githubusercontent.com/assets/11017516/21291596/eec67a48-c520-11e6-8423-3d292d17a08e.png)

so，what is the best to way to config log level or log path，
and does it support logback config？

thanks。

**Comment by jonesde** [comment]
The problem with the log4j configuration in general is that it gets initialized before moqui-framework starts up and adds its classloader to augment the classpath and allow override of configuration files (in runtime/classes, or a classes directory in any component; the same applies to the lib directories for jar files). You can explicitly add a file on start using -cp or use other approaches but it depends on how you are running moqui.war.

BTW, your directory structure is really odd, like you were running from inside the moqui/framework directory.

No, Moqui does not support logback configuration because logback is a very different logging framework and not used by default. I looked into it at one point but there are not significant benefits to logback over log4j2. Moqui itself does all logging through SLF4J but there are certain other libraries commonly used by Moqui (such as ElasticSearch 5) that use log4j2 directly.
