### ISSUE TITLE
Translation for the same word in different context

### ISSUE THREAD

**Issue by mckhoi** [moqui/moqui-framework#172]
Hi David,

Happy New Year, 2017.

I have the problem, that I cannot translate the same English word on diffenrent pages in diffenrent words on other language.

The common problem is that, one word on English can have different meaning in diffenrent context. So for the domain eCommerce the same English word is differently translated than for the domain Manufacturing.

For the framework, I think it could be helpful with a new feature extension in entity LocalizedMessage, that we can insert also the name of the componnent as a special translation? Or maybe in detail also the name of specific page(URL)?

Best Regards,
Khoi Tran

**Comment by shendepu** [comment]
Khoi,

You may define a key for the word and translate it in all support languages.

E.g. Order may mean in verb or noun which translate to different words in some language like Chinese. So a __order_verb__ and __order_noun__ may be defined and used for translation, and both them are translated to "order" in English, but different word in Chinese.

???? iPhone

? 2017?1?2??21:48?Khoi Tran <notifications@github.com<mailto:notifications@github.com>> ???


Hi David,

Happy New Year, 2017.

I have the problem, that I cannot translate the same English word on diffenrent pages in diffenrent words on other language.

The common problem is that, one word on English can have different meaning in diffenrent context. So for the domain eCommerce the same English word is differently translated than for the domain Manufacturing.

For the framework, I think it could be helpful with a new feature extension in entity LocalizedMessage, that we can insert also the name of the componnent as a special translation? Or maybe in detail also the name of specific page(URL)?

Best Regards,
Khoi Tran

-

**Comment by jonesde** [comment]
The way to do this in Moqui (and there is a discussion in the LinkedIn group with more details) is to add a context to the original string to localize. Anything after a hash (#) in the original string will be considered a context. This is important because separate translations by context are not always needed and if one is not found it falls back to any translation found for the original string before the hash.

For example the 'Go#Page' original string will cause the localize method to look for translations for 'Go#Page' and if none are found it looks for plain 'Go' and if none is found then is uses just 'Go' (the part before the context) for the output string to use. As with all translations the result is cached to avoid having to all these DB lookups over and over.

**Comment by shendepu** [comment]
David - it might be type wrong.  It should be double "##", as "Go##Page" as example.

**Comment by jonesde** [comment]
Thank you Jimmy, you're absolutely correct, it is a double hash (##) that is used for the context separator so the Go example should be 'Go##Page'. As I recall there were issues with a single hash as various existing groovy strings used it.
