### ISSUE TITLE
Could not find service with name [create#mantle.party.Party]

### ISSUE THREAD

**Issue by Regu058** [moqui/moqui-framework#182]
While creating User from the create#UserAccount  service am calling  the moqui service which is for creating party entry in party table and am using the same partyId for UserAccount table, For some time while creating User its throw this error "Error running groovy script (org.moqui.service.ServiceException: Could not find service with name [create#mantle.party.Party]):" .

I guess this error because of ServiceSync 

 **### def call_service_result = ec.service.sync().name("create#mantle.party.Party")
           .parameters([partyTypeEnumId:'PtyOrganization', disabled:disabled]).call()**

Please give some input to rectify this issue.

![partserviceerror](https://cloud.githubusercontent.com/assets/25477226/22501329/5df208ac-e88e-11e6-9663-38eb9a3c15b2.png)

**Comment by jonesde** [comment]
Which version of Moqui Framework was this from?

**Comment by Regu058** [comment]
Moqui 1.6.

Is that because of service sync fail?
If that is the case how we can fix this.....

And for your Information, By this time changing updated version also not possible from my side.

**Comment by jonesde** [comment]
I suppose the fix could be back ported, but there are a lot of code changes for optimization and cleanups in 2.0.0 so it wouldn't be a straight cut-and-paste back port.

If this is from the issue I have in mind you shouldn't see it in production, only in development mode when there is a timeout on the framework artifact caches (like service and entity definitions). While there are other reasons I'd recommend updating to 2.0.0 or even the latest snapshot, and in general not modifying the framework when building applications and such (99% of the time there are other/better ways of doing what you need), for this issue it isn't necessary as it is caused by the frequent cache clearing and artifact reloading in dev mode.
