### ISSUE TITLE
entity.record.count cache not cleared when update operation done on entity records

### ISSUE THREAD

**Issue by visvendra** [moqui/moqui-framework#197]
Here is the case where I am having this-

- Getting count
```
<entity-find-count count-field="totalStoresWithImages" entity-name="ProductStore" cache="true">
	<econdition field-name="productStoreId" operator="not-equals" value="_NA_" />
	<econdition field-name="locationImagePath" operator="is-not-null" />
</entity-find-count>
```
- Updating some records and putting locationImagePath. And now when I again fetch count it same count of product stores as it was before update: which is incorrect. It should be lesser. So, the problem is with Cache, because it is fetching from cache and it holds old value of count.

So, entity.record.count cache should get cleared when update is done. similar to [https://github.com/moqui/moqui-framework/issues/22#issuecomment-286461598](https://github.com/moqui/moqui-framework/issues/22#issuecomment-286461598)

**Comment by jonesde** [comment]
Entity (database) cache clearing is complex and count caches are actually not similar to list caches at all, which in turn are not similar to one caches. Each uses different algorithms to selectively clear cache entries, and it is important to understand that there is a lot of overhead in selectively clearing caches.

I added a test similar to your case and going beyond it to test the set to not null and reset to null. This is a tricky issue and looking into it more there is no way to selectively clear a count cache. In commit #d876e66 it simply clears the entire count cache. That fixes the issue, but does so with a hammer since we have no other tool.

In general caching only makes sense when you have a high read to write ratio. This strikes me as one where that rule may not apply and your code may actually run SLOWER overall by using the cache.

More generally I have yet to find a good use case for cached counts and am considering deprecating this feature, ie never caching count finds.
