### ISSUE TITLE
How to call the Service Synchronously

### ISSUE THREAD

**Issue by Regu058** [moqui/moqui-framework#204]
For my scenario need to generate the ID's(Bill Number) sequentially. So am saving last generated Id in one table for next time I will get the last generated id and adding 1 and use  that for some transaction again updated the last generated Id , In this case with same URL two different user logged in and they are billing in the same fraction of second they where getting same Bill Number for both the bills.

 And I have created the Service for getting last generated ID and adding with 1(LastGeneratedID +1) if I call this Service Synchronously Hope I will get different ID's even they are billing in the same fraction of time.

 I tried in the below mentioned way It now working, means service call is working fine but again Am getting same ID, Please give your input to resolve this issue.

The way am calling the service:
----------------------------------
<script>       
       Map resOut =ec.service.sync().name("moqui.invoice.POSServices", "get", "ResolutionSequence")
                    .parameters([organizationId:branchId]).call()
</script>

**Comment by jonesde** [comment]
That isn't what 'synchronous' means... what you are describing is 'synchronized' as in with a semaphore so only one instance is running at a time. This is supported for Moqui services using a semaphore record in the database, but isn't the right solution to what you are describing.

The proper approach for this is to do a for update query on the record before updating it so that you get an exclusive lock on the record in the database, and it will wait until other DB transactions are completed before it returns the record that is locked for update (so nothing else can change it until this tx commits or rolls back).
