### ISSUE TITLE
Cache Problem with distributed Instance

### ISSUE THREAD

**Issue by Regu058** [moqui/moqui-framework#208]
Hi, 
 We are deploying multiple moqui applications in multiple Instances based on the business need, by pointing the same DataBase. In this case, if the 'Sequence Number' of any of the entity  is updated from one instance in DB, it is not reflected in other instance because the current sequence values is picked up from that instance cache so that the time of insertion is throwing PrimaryKeyViolation exception.

Hope you understand the problem, Please help us fix this.

 If you need more clarification on this issue we will communicate through call.

**Comment by jonesde** [comment]
Which version of moqui-framework are you using? Which database are you using? There may also be something caused by a particular configuration such as the transaction isolation.

Based on your description I can only guess at the problem as it is not sufficiently detailed, but it sounds like you are running into issues with the Entity Facade's sequencedIdPrimary() method (also accessed through EntityValue.setSequencedIdPrimary()) which uses the SequenceValueItem entity to keep track of the highest seqNum reserved (by any instance).

I and others have used this with multiple app server configurations backed by a single database instance (and all using the same database on that instance) and I've done load tests with both MySQL and DB2 with multiple app servers. In other words, this has been tested the question is why you are running into issues, and since it wasn't in your original description what is the particular error happening in your case. 

We could start with log files, but think of this in terms of a sufficient level of detail to reproduce the issue.

**Comment by jonesde** [comment]
No response and haven't seen this issue in other testing so closing this issue.
