### ISSUE TITLE
Demo does not login OOTB

### ISSUE THREAD

**Issue by dhcdata** [moqui/moqui-framework#224]
Issuing the following commands:
`git clone https://github.com/moqui/moqui-framework.git`
`cd moqui-framework`
`./gradlew load`
./gradlew run`

I end up with an error free deployment.
When attempting to login with username: `john.doe` and password: `moqui`, **I am returned to the login page and the following logs**

`17:03:51.623  INFO 728890494-42                 o.m.i.c.UserFacadeImpl Created new Visit with ID [100007] in session [node01wfrcydesbxl7i8zp5eq91bnf8]`
`17:03:51.643  INFO 728890494-42               o.m.i.e.EntityFacadeImpl Found entities in 9 files in 14ms`
`17:03:51.644  INFO 728890494-42               o.m.i.e.EntityFacadeImpl Found 0 view-entity definitions in database (DbViewEntity records)`
`17:03:51.647  INFO 728890494-42               o.m.i.s.ScreenRenderImpl Transition Login/login in 24ms, redirecting to screen path URL: http://localhost:8080/apps/AppList`
`17:03:51.660  INFO 728890494-10                 o.m.i.c.UserFacadeImpl Created new Visit with ID [100008] in session [node06lbkgm0mfto91wj3q06axpkgg9]`
**`17:03:51.661  INFO 728890494-10               o.m.i.s.ScreenRenderImpl Screen at location component://webroot/screen/webroot/apps/AppList.xml, which is part of [apps, AppList] under screen component://webroot/screen/webroot.xml requires authentication but no user is currently logged in.`**
`17:03:51.674  INFO 728890494-72                 o.m.i.c.UserFacadeImpl Created new Visit with ID [100009] in session [node01goz6pwaq4nalluk99duaow0g10]`
`17:03:51.789  INFO 728890494-72               o.m.i.s.ScreenRenderImpl Login in 114ms (text/html;charset=utf-8) session node01goz6pwaq4nalluk99duaow0g10`

When I use `john.doe` and an incorrect user name, I appropriately get a `Username john.doe and/or password incorrect` Exception in the logs (though nothing in the browser).

Am I missing a step?

**Comment by jonesde** [comment]
If you are getting a new Visit with each request (which you are) then the browser is losing the session. Either cookies are disabled or there is a cookie conflict which can happen if you have a secure cookie with the same name and for the same domain as what you're trying to use for a non-https connection. Try clearing your cookies, or the specific localhost JSESSIONID cookie, or try an incognito/private window in your browser (for the separate, temporary cookie space).

**Comment by dhcdata** [comment]
This is likely something that would only show up in development then, correct?

**Comment by jonesde** [comment]
This is really between browsers and servlet containers. Moqui Framework uses both but you can choose from various options for either, and Moqui leaves it up to the servlet container to manage sessions (or a plugin if you use something like that). 

This issue seems to be a newer one in Chrome when they switched for more security to not allow plain http responses to set cookies on top of those from https responses. It is a browser issue that we as developers need to know about, but there isn't much we can do about it. Another recent annoying change in Chrome is that hard reloads no longer reload JS and CSS files unless development tools is open and you have the setting to clear/reload files on a reload (or you clear the whole browser cache...). For support this is also important to be aware of us users may end up with stale JS/CSS after a server update.

I've actually seen it more on test/staging servers with multiple instances on multiple ports because cookies are by domain name regardless of port.
