### ISSUE TITLE
MoquiInit.properties does not affect runtimePath or confPath

### ISSUE THREAD

**Issue by dhcdata** [moqui/moqui-framework#227]
Changing `moqui.runtime` or `moqui.conf` values in `MoquiInit.properties` doesn't change the value of runtimePath or confPath used at start.  The notes in `MoquiInit.properties` suggests that it should.

in `MoquiStart.java` line 346 ends up null
`        URL initProps = cl.getResource("MoquiInit.properties");`

however, the following picks up the correct values:
`        URL initProps = cl.getResource("WEB-INF/classes/`MoquiInit.properties");`

**Comment by jonesde** [comment]
This is used in different ways depending on how you run Moqui. How, exactly, are you running it? In other words are you running from the command line with java -jar, dropping the war file in a servlet container, running in a Docker image, running the gradle/spock tests?

**Comment by dhcdata** [comment]
java -jar

**Comment by jonesde** [comment]
Yes, that is how it works. If you run plain java -jar moqui.war the MoquiInit.properties file won't be on the classpath because it is not in the root directory of the war file (in that case treated as a jar file). You can add it to the classpath on the command line or add it to the war file.

It is in the WEB-INF/classes directory in the war file so that when the war file is dropped into a servlet container like Jetty or Tomcat it will run in production mode by default, ie using the MoquiProductionConf.xml file (unless you change MoquiInit.properties before building the war file).

We don't want it to default to the production config for 'java -jar moqui.war' because that is the primary way to run it in development.
