### ISSUE TITLE
helm chart for moqui

### ISSUE THREAD

**Issue by dhcdata** [moqui/moqui-framework#229]
I've created a [moqui helm chart](https://github.com/dhcdata/bitnami-charts/tree/moqui/incubator/moqui) to deploy a tomcat container running the Moqui-framework into a kubernetes cluster.

This makes it easy to maintain a separation of concerns with your own configuration files and containers for both moqui and tomcat, separately.

It would be great to see a new repository under moqui to deal with deployment strategies (ie pull the docker folder from moqui-framework).  If that's not preferred, I can add a PR under the existing docker folder.

I'm working on expanding this to include the kube-lego (automatic lets encrypt) and nginx-ingress to deal with routing by configuration.  I look forward to moving this forward.

Thanks!

**Comment by jonesde** [comment]
I'd recommend sharing this in your own public repository on GitHub. We may eventually add more sample configurations for various deployment approaches and tools, but only if they are refined, tested, and maintained. I don't currently use Kubernetes so as a moderator without significant effort I couldn't test or maintain this. 

There are huge numbers of such tools, made worse by the major hosting providers creating their own variations on the standard Docker tools (like Docker Swarm and Compose). It is great if people share what they've setup for different tools, but it doesn't make sense to have them in the core project.

BTW, I'd recommend following the pattern in the OOTB Dockerfile (in moqui-framework/docker/simple). You can of course run it in Tomcat instead of the embedded Jetty, but for simplicity and consistency that helps harden it over time this is the default approach and the recommended one.
