### ISSUE TITLE
How to cluster deploy with multi-tenant?

### ISSUE THREAD

**Issue by hanyou** [moqui/moqui-framework#245]
Did you have some document about how to cluster deploy with multi-tenant?

**Comment by jonesde** [comment]
The multi-tenant functionality was removed in release 2.0.0 and replaced with multi-instance management (OOTB implementation currently limited to Docker and MySQL for automated provisioning)?

I haven't yet done a multi-instance deployment on a cluster, ie something like a Docker Swarm cluster or with other similar tools.

For simpler cases you could manually assign instances to different Docker servers with the existing instance management screens and services.

**Comment by hanyou** [comment]
why did you remove multi-tenant feature?

**Comment by jonesde** [comment]
Because:

- it was terribly complex with tenant specific complications throughout the framework (a lot of work to maintain); eliminating this feature, which no one seemed to use or care much about, eliminated thousands of lines of code (including framework tool code along with screens and services and such) from the framework
- the approach of multiple tenants in a single application instance, even with separate databases, has significant security concerns and does not allow for custom code per tenant for security reasons (ALL code running on the server has to be reviewed to make sure it doesn't do anything explicit to operate on other tenants than the active one, ie the one the user authenticated with)
- container technology has matured and is commonly used, and over time the demands for this and actual use on Moqui this way is wide spread
- container based deployments are far more secure (different instances are fully isolated) and there are many tools available to manage a wide variety of different deployment patterns across many platforms

There was a bunch of discussion about this in the Moqui Ecosystem forum on LinkedIn. You can find more information about it there, if you care. If you don't have access to LinkedIn forums I'm sorry, but there isn't much I can do about that.

**Comment by hanyou** [comment]
Whether the forum can be set to visit the region, hoping to develop to the Chinese region.

**Comment by jonesde** [comment]
There are quite a few Moqui users in China, and even a few service providers. The decision to use a LinkedIn group was made a long time ago and since then LinkedIn has done things to continue operating in China. I don't know much about it, but this article has some interesting information and it looks like people accessing LinkedIn directly in China (with no VPN) can access groups but not start or join them:

https://www.nytimes.com/2014/10/06/technology/to-reach-china-linkedin-plays-by-local-rules.html

There are also some Google groups setup for Moqui that can be used for discussions and questions, but not many people are subscribed to these and right now they are mainly used for commit notifications.

**Comment by hanyou** [comment]
thanks
