### ISSUE TITLE
Did you have Moqui 2.0 documents?

### ISSUE THREAD

**Issue by hanyou** [moqui/moqui-framework#247]
I download MakingAppsWithMoqui-1.0.pdf form website, now you release 2.0, where do i download document?

**Comment by shendepu** [comment]
@hanyou I think David would like issues to be related with bugs, real issues, feature request to the corresponding repository, rather than general questions. Those general questions can be asked on StackOverflow or LinkedIn group. 

I would suggest you walk through StackOverflow (search with keyword `moqui`), and LinkedIn group (If you can't access, you shall find a VPN (paid maybe) to connect). 

There are repositories under moqui umbrella  
- [moqui-framework](https://github.com/moqui/moqui-framework)
- [moqui-runtime](https://github.com/moqui/moqui-runtime)
- [mantle-udm](https://github.com/moqui/mantle-udm)
- [mantle-udm](https://github.com/moqui/mantle-usl)
- [moqui-elasticsearch](https://github.com/moqui/moqui-elasticsearch)
- and more (you may find the list in https://github.com/moqui/moqui-framework/blob/master/addons.xml) 

Each repository addresses different concerns, and issue shall be created in corresponding repo. 

To your question, MakingAppsWithMoqui-1.0.pdf was made several years ago, David did not have time to update it and from earlier communication on such question, it is unlikely to be updated in near future. 

But the source code is all there, you may find your best way to exploit them. 

From my experience, it takes more than half a year to get some level of understanding on moqui-framework if you are experienced in J2EE. Do not try to compare the concept of Spring, Structs  with moqui-framework since they are very different. Moqui provides the one-stop solution. And it may take years on mantle artifacts (udm, usl) since they are more business related like ERP, ecommerce, HR, CRM, Finance etc.
