### ISSUE TITLE
Error to create record in EntityAuditLog

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#265]
To reproduce:
1. Create a new invoice or find a existing one
2. Change an Amount to 100 and update the invoice
3. A record will be created in EntityAuditLog, This is expected
4. Keep all values unchanged in the invoice and update it again.
5. Another record will be created, This is not expected.

I used PostgreSQL

It is caused by the Amount 100  becomes 1E+2 in EntityValueBase.refresh().

**Comment by jonesde** [comment]
This is fixed in commit d7b805e0. The core issue was that BigDecimal.equals() has some quirks, as does getting BigDecimal values from the database which is the reason stripTrailingZeroes() is used... but that has side effects like settings a negative scale for values like 100 (hence the 1E+2). The entity facade code is now a little smarter about that, setting the scale to zero if it is negative, and while that generally resolves this issue it isn't guaranteed with BigDecimal the audit log stuff now uses compareTo() for BigDecimal instead of equals().

BigDecimal is one of the bigger farces in the Java world, all the bugs over time plus quirks like these. Life would be WAY easier if BigDecimal.toString() did what toPlainString() does, and if equals() did what compareTo() does, and so on. It makes BigDecimal behave differently from the various other Number classes requiring all sorts of special handling code.

**Comment by zhangwei1979** [comment]
Hi David,

Do you think it is useful we add a flag in EntityAuditLog to indicate it is caused by updating or creating?

Kind Regards,

Wei
