### ISSUE TITLE
Artifact authorization check on entity fails after logged with another user in service

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#267]
For a simple test case as below, the logged in user is `testA` which in not administrator. and can run it successfully that pass authorization check on entity `moqui.security.UserAccount`. 
```
<service verb="get" noun="MyUserAccount" authenticate="anonymous-view">
    <actions>
        <set field="userId" from="ec.user.userId"/>
        <entity-find-one entity-name="moqui.security.UserAccount" 
             value-field="userAccount" cache="true"/>
    </actions>
</service>
```

And same service but it login with another user `testB` which has same permission with `testA`
```
<service verb="get" noun="MyUserAccount" authenticate="anonymous-view">
    <actions>
        <script>
               ec.user.loginUser('testB', 'test')
        </script>
        <set field="userId" from="ec.user.userId"/>
        <entity-find-one entity-name="moqui.security.UserAccount" 
              value-field="userAccount" cache="true"/>
    </actions>
</service>
```
Then artifact authorization check on entity `moqui.security.UserAccount` fails with error 
```
 Artifact authorization failed: User testB is not authorized for View on Entity moqui.security.UserAccount
```
And when logged user is `testB`, the service above with relogging user runs successfully  

And this can be reproduced by put the service under rest api like below
```
<resource name="test" require-authentication="anonymous-view">
    <method type="get">
          <service name="test.UserServices.get#MyUserAccount"/>
    </method>
</resource>
```

**Comment by jonesde** [comment]
This is the expected behavior. The anonynmous-view authenticate (which results in a call to ArtifactExecutionFacadeImpl.setAnonymousAuthorizedView()) sets view authorization only for the currently logged in user, or an anonymous user (no user, treated internally as logged in as an anonymous user for authentication/login checks). If you manually login a user using the API and you want that user to have authorization like this you'll have to make additional method calls (ie call setAnonymousAuthorizedView() or other methods as needed).

**Comment by shendepu** [comment]
I see. Thanks for the explaination.
