### ISSUE TITLE
Artifact entity is needed

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#275]
Hi,
There are ArtifactGroup,ArtifactGroupMember entities definition in SecurityEntities.xml and artifactName is a pk field in ArtifactGroupMember.
 Is it better to introduce a definition Artifact and with the fields   artifactId,artifactName,artifactTypeEnumId,nameIsPattern,inheritAuthzfilterMap. then the ArtifactGroupMember with artifactGroupId,artifactId,fromDate,thruDate ?
such that I can define the artifact first, then bind them to the group.

**Comment by jonesde** [comment]
Why? This would basically just make the artifactName reusable across multiple records, but I haven't run into this being an issue even with fairly complex authorization setups. This also makes UI, queries, etc more complex, not a small change, and would require database migration for updating existing systems.

In other words, there has to be a really darn good reason to do stuff like this.

**Comment by WillWei1983** [comment]
What we are considering is that the system developer(who is more familiar with the data model) can setup the record in Artifact entity, then the business consultan(who maybe don't know what the data model of moqui) then can bind the artifact record to  ArtifactGroup with an UI but not creating the ArtifactGroup record first then creating the ArtifactGroupMember record cause the business consultan don't know what record to be created. 

But considering this is not a small change then keep it as is will be much better, we can just simply introduce this entity by ourself for the business consultan to copy the data to the existing ArtifactGroupMember with an UI.

**Comment by jonesde** [comment]
Perhaps a better, and more flexible, approach would be to add some forms specifically for different types of artifacts to add to a group and allow search among artifacts that exist (by regex, defaulting to case-insensitive partial strings as done already for entity and service searches).

I thought about doing this a while back but didn't because what seems to happen is a developer sets up the artifact groups and then system admin sorts can setup authorizations based on them.
