### ISSUE TITLE
Redundancy data is generated when using the server-static in a form-list

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#294]
When I use the server-static in a form-list, then the vue form-list will use the fetchRow() method to get the data from the result of the entity-find in the form-list.
but the data is redundancy by adding listName+"_entry",listName+"_index",listName+"_has_next"

I trace the code, it is generated by below code
// NOTE: always call AggregationUtil.aggregateList, passing aggregateList to tell it to do sub-lists or not
            // this does the pre-processing for all form-list renders, handles row-actions, field.@from, etc
            return formInstance.aggregationUtil.aggregateList(listObject, includeFields, aggregateList, ecfi.getEci())
 then in the method
processAggregateOriginal in AggregationUtil.java
if (listEntryName != null) {
            context.put(listEntryName, curObject);
            context.put(listEntryName + "_index", index);
            context.put(listEntryName + "_has_next", hasNext);
        } else {
            context.put(listName + "_index", index);
            context.put(listName + "_has_next", hasNext);
            context.put(listName + "_entry", curObject);
        }
when putting this to the context, it will also putting to the contextTopMap so that the resultList have this fields.
what is the purpose of adding this to the context? as when using the server-static way to the get the data, I don't need it.

**Comment by jonesde** [comment]
For now don't use the form-list.@server-static attribute, it is experimental at best and isn't even close to complete and hasn't been tested since the early efforts on it. Various things like client side (JavaScript) date and number formatting aren't yet finished, and anything other that display only forms won't even be close to working.

Those fields that aren't needed for server-static are needed for server side form rendering. I may eventually add something to either trim them or not add them (would require the code knowing that it is getting data for a server-static request). For now if you're playing with this, yes it is inefficient.

At some point I'd like to do more work on the many things we can do with Vue JS but unfortunately it is really low on my priority list and totally unfunded (ie no client requests related to this).
