### ISSUE TITLE
Wrong sub-select WHERE clause, added entity-alias as prefix.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#300]
I created an [#299] to reproduce this bug.
Sometime generated WHERE clause for subquery use `entity-alians.field-name`,  It should be `field-name` only.
The unit test contains two case, one will fail, another will pass.
I debugged into `FieldValueCondition.java:69`,  In the failed case it got wrong `FieldInfo`

**Comment by jonesde** [comment]
It looks like the fix ended up being in ConditionField.java, making sure the internal/cached FieldInfo entity matches the entity where the field is actually being used. That's a good change. I'm making one small change to it to compare ed.fullEntityName instead of just ed (EntityDefinition has no equals() method override, so this could get false negatives by comparing objects by the Java Object.equals() default of comparing memory addresses, especially in dev mode as EntityDefinition objects are cleared from the cache and reloaded).
