### ISSUE TITLE
Swagger UI for Orders & Shipment Services doesn't show up

### ISSUE THREAD

**Issue by innatepassion** [moqui/moqui-framework#330]
Getting No response When attempting to view swagger ui for Orders & Shipments.

![moqui swagger ui orders](https://user-images.githubusercontent.com/4814380/44389614-eef40d00-a548-11e8-84d6-8635e86180c2.png)
![moqui swagger ui shipments](https://user-images.githubusercontent.com/4814380/44389618-f1566700-a548-11e8-83ae-7faa6c93fccc.png)

**Comment by jonesde** [comment]
Please note that this is not a Moqui Framework issue and doesn't belong here. It is a mantle-usl issue and now fixed in commit 72a2dfa in that repository.

For future reference the most common issue is with parameters that map to a JSON array type and Swagger UI is buggy when an array type field has no definition of what is in the array. There is a warning log message that showed for these, it looks like:

    Parameter orderIdSet of service mantle.shipment.ShipmentServices.get#ShipmentPickPackInfo is an array type but has no child parameter (should have one, name ignored), may cause error in Swagger, etc

The place issues like this should be filed is on moqui.org as a request. Please see:

https://www.moqui.org/m/docs/moqui/Community+Guide
