### ISSUE TITLE
call ws with swagger ui return 401 & there is no uniqe property for entity fileds

### ISSUE THREAD

**Issue by amirmf** [moqui/moqui-framework#335]
is there any property to make a field unique in entity ?

**Comment by aabiabdallah** [comment]
You can create an unqiue index in an entity. Example:

```
<index name="uniqueIdx1" unique="true">
   <index-field name="field1"/>
</index>
```

Swagger 401 error is most likely to insufficient permissions. More details are required to confirm.

**Comment by jonesde** [comment]
I don't see sufficient detail here to answer a question and know that the intended question is being answered. Unless @amirmf follows up I'll close this issue.

**Comment by amirmf** [comment]
Hi,
if you call any of your post rest api you will get 401 response 

you can also try it on your online demo 
sample post api:
https://demo.moqui.org/toolstatic/lib/swagger-ui/index.html?url=https://demo.moqui.org/rest/service.swagger/mantle/parties#!/parties/post_person

i think it's because on your post call framework is looking for moquiSession.

**Comment by jonesde** [comment]
Security for REST requests has been tightened so that you must either authenticate for each request (with api_key or username/password) or to rely on a session being in place, which isn't a best practice for most REST APIs anyway, you must supply a moquiSessionToken to protect against session hijacking.

The Swagger UI is great for reference but there are better tools for testing the REST API. You can supply an api_key in the Swagger UI but currently that is the only way to run REST requests through it.

I don't know if that resolves this issue but it is a mess, vague and covers multiple topics, so I'm closing this. In general issues on GitHub should not be used and are disabled for all repositories except moqui-framework to push toward using HiveMind on moqui.org. The only reason this issues here are not yet disabled is because of older issues that haven't been moved yet but that might still be important. Please see:

https://www.moqui.org/m/docs/moqui/Community+Guide

Also when filing issues please make them clear or they are impossible to look into or answer. Please see:

https://www.moqui.org/m/docs/moqui/Issue+and+Pull+Request+Guide
