### ISSUE TITLE
some porblem with Authorizations

### ISSUE THREAD

**Issue by cleverdb** [moqui/moqui-framework#343]
version 2.1.0 . 
How do I configure permissions to each screen CRUD?

This is how I configure it. view is ok，but create form is disabled

![image](https://user-images.githubusercontent.com/36070433/48927866-b16e9980-ef14-11e8-8f28-b32b615afa72.png)

I hope I can get your help.

**Comment by jonesde** [comment]
The only distinction supported for authorization at the screen level is View vs All. This is done by looking at screen transitions with no service-call and no actions, or read-only="true" to know they can be allowed when only View is allowed, otherwise the All authz action is required. 

To make this more convenient there are certain service name verbs Moqui looks at for transitions with a service-call element to treat them as read-only: "find", "get", "search", and "view".

This could possibly be done for transitions with a service-call only with the verb "create" but that is not currently supported, at least for what I'm guessing you're trying to do based on how screens, transitions, and services currently work.

**Comment by cleverdb** [comment]
Thank you for your answer,I may not express what I mean, the need is this: a user has a screen's view and create permissions, but no update and delete permissions, how should I configure?  according to the above image configuration, the user only has the view permissions, no create permissions.

**Comment by jonesde** [comment]
Yes, that's what I answered.

**Comment by jonesde** [comment]
If you want to go forward with this please file a new feature request on moqui.org. See:

https://www.moqui.org/m/docs/moqui/Community+Guide

To help with clarity in issue reports or new feature requests so that something can actually be done about them, please see:

https://www.moqui.org/m/docs/moqui/Issue+and+Pull+Request+Guide
