### ISSUE TITLE
What is the custome changes to the Bitronix?

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#350]
I am trying to use a APM glowroot with Moqui.
It works fine for glowroot v0.9.24, but from the v0.9.25, it always throw excpetions cause by Bitronix when Moqui init the datasource.

below is the link of glowroot release
https://github.com/glowroot/glowroot/releases?after=v0.10.0

**Comment by jonesde** [comment]
There are no changes to Bitronix in the jar included in moqui-framework, the jar file is there because the latest from Bitronix is only available in source through GitHub (ie no published releases in Maven Central or JCenter). I've never tried Glowroot, and without seeing the exception couldn't even guess at what might be going on.

**Comment by WillWei1983** [comment]
Updated: It's glowroot's issue. can be closed
