### ISSUE TITLE
Login issue when using multi moqui servers

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#353]
I'm deploying 1 Moqui App with following server:
- 1 DB using mysql
- 2 Moqui servers, named **server01** & **server02**
- In future: will use a Nginx as a SSL termination and proxy.
- I don't use moqui-hazelcast as I understood that it's not required, just for performance improvement.

**Test scenario:**
1. Login to Moqui App on **server 01** (url: http://server01:8080/), username = **user01**: ok as expected
2. Login to Moqui App on **server 02** (url: http://server02:8080/), username = **user01**: ok as expected
3. Doing transaction on both servers: as expected
4. Logout **user01** in **server 02**
Can't not do transaction in **server 01** with **user01** anymore because it's logged out from system => OK as expected
5. Do Login **user01** to Moqui App on **server 01**, expect that login is OK. However, system redirects to Login screen.
Error message in log: 
`User user01 is authenticated in session but hasLoggedOut elsewhere, logging out` 

Is this situation a normal behavior of Moqui? Am I wrong when using multiple Moqui server for 1 App?

**Comment by WillWei1983** [comment]
Hi, I am wondering how to keep the cache sync without the moqui-hazelcast. need to implement a entity distributed cache invalidation by self?  the performance is not very good when include the moqui-hazelcast ,especially when using the distributed cache. Would it be better to use the client-server mode of hazelcast instead of running in the same instance with Moqui?

**Comment by jonesde** [comment]
This isn't a bug or improvement sort of issue, it is more of a question and should go on the mailing list (moqui@googlegroups.com). This is because more people will see, it can actually be discussed, and as I've mentioned before I intend to shut down issues here on GitHub because they are a misused dumping ground.
