### ISSUE TITLE
[Question] How to make use of the service-facade.service-location with Json RPC call

### ISSUE THREAD

**Issue by lightning-pro** [moqui/moqui-framework#385]
Hi,
I make a RPC call by below way, when this service was called, it will do the RPC call.
`<service verb="test" noun="JsonRpcCall" type="remote-json-rpc" location="http://10.0.8.77:8081/rpc/json" method="org.moqui.impl.BasicServices.find#Enumeration">
        <in-parameters>
            <parameter name="authUsername" default-value="account-rpc"/>
            <parameter name="authPassword" default-value="moquirpc"/>
            <parameter name="enumTypeId"/>
        </in-parameters>
    </service>`

but this is not good enough because of the hard code ip port in the location. from the xsd for this location is 

> For remote services this
                    is the URL of the remote service. Instead of an actual location can also refer to a pre-defined
                    location from the service-facade.service-location element in the Moqui Conf XML file. This is
                    especially useful for remote service URLs.
I try to define the service-facade.service-location and use it like 

`<service verb="test" noun="JsonRpcCall" type="remote-json-rpc" location="${main-json}" method="org.moqui.impl.BasicServices.find#Enumeration">
        <in-parameters>
            <parameter name="authUsername" default-value="account-rpc"/>
            <parameter name="authPassword" default-value="moquirpc"/>
            <parameter name="enumTypeId"/>
        </in-parameters>
    </service>`
but it didn't work. any suggestions on how to make use of this service-facade.service-location definition ?

BTW, if the authUsername and authPassword  are config in the MoquiConf.xml would be better ?

**Comment by jonesde** [comment]
In general the JSON-RPC stuff is very old and to my knowledge has never been used for anything serious (ie other than proof of concept many years ago). If you use a predefined service location (in a service-facade.service-location element in Moqui Conf XML) you don't use the ${}, just the name of the location.

More generally I'd recommend using the RestClient class instead of defining a service with the type 'remote-json-rpc'. While that can be useful in some circumstances and fits nicely into the utopia idea of not caring where services are located (ie to allow moving services to a remote server by just overriding a service definition), for most use cases it is not helpful.

BTW, please send questions like this to the 'moqui@googlegroups.com' mailing list. GitHub issues are not a good support tool, largely because people tend not to respond and they site open for months before a maintainer force closes them. See:

https://www.moqui.org/m/docs/moqui/Community+Guide
