### ISSUE TITLE
component-set framework does not work.

### ISSUE THREAD

**Issue by jeffsnff** [moqui/moqui-framework#400]
When trying to download the component set `framework` it no longer downloads because of the `moqui-elasticsearch`. From what I heard from my Project Manger, this has been built into the system now. 

I ran a test, and deleted `moqui-elasticsearch` from the framework component set and ran the code `./gradlew getComponentSet -PcomponentSet=framework` again, and it worked flawlessly. 

I was wondering if I could go ahead and submit the code to fix this issue.

**Comment by mkdecision** [comment]
Jeff,
Make sure you review https://groups.google.com/forum/#!forum/moqui. It has
commonly asked questions. Here are a few relevant topics on ElasticSearch.

https://groups.google.com/d/msg/moqui/jFpO_5ydvGc/u_R9hVFeAgAJ
https://groups.google.com/forum/#!topic/moqui/jFpO_5ydvGc
https://groups.google.com/forum/#!topic/moqui/SkOII0JpPWY





[image: facebook] <https://www.facebook.com/mkdecision/>
[image: twitter] <https://twitter.com/MKDecision>
[image: linkedin] <https://www.linkedin.com/company/mkdecision/>
[image: instagram] <https://www.instagram.com/mkdecision/>
Guru Dharam Khalsa

Chief Operating Officer

Founder | MK Decision

Read My Spotlight
<https://mkdecision.com/blog/2019/10/25/a-family-founded-fintech/>
*w* 844 888 5565 | *c *602 810 0749
gurudharam.khalsa@mkdecision.com
https://mkdecision.com/
Refer a friend and get $100 when they sign up!
<https://mkdecision.com/contact/>

NOTICE: This communication may contain privileged or other confidential
information. If you are not the intended recipient, or believe that you
have received this communication in error, please do not print, copy,
retransmit, disseminate, or otherwise use the information. Also, please
indicate to the sender that you have received this communication in error,
and delete the copy you received. Thank you.

ᐧ

**Comment by jonesde** [comment]
This was an issue, now fixed in commit a7e33a63. That was only the surface of the issue of those old component sets having been neglected and I updated them to include all of the released components (aside from some no longer maintained).

In general I would NOT recommend using these component sets. You'll be pulling in a lot of stuff that changes how the framework and other parts of the system behave and if you don't understand what you're doing with the component and also configure it for your needs then you're more likely to have issues than if you stick with a minimal set of cherry picked components for your needs.

For example the moqui-hazelcast component is for clustered server deployments and because it changes certain things like cache clearing to be asynchronous it will cause the automated tests in moqui-framework to fail (along with changing web session behavior, distributed service execution behavior, etc, etc).

The whole point of splitting things into optional components is to keep systems as small as possible. If there are features you need, great, add the component. If you don't it's best to leave them out. That falls into the general philosophy of business systems where **code** is not an asset, it **is a liability** and always has acquisition, configuration, deployment, maintenance, and support costs.

I tested the updated addons.xml file from a fresh checkout and the framework, mantle, apps, and ecosystem components sets are all working now, but I still wouldn't recommend using them in general.
