### ISSUE TITLE
Consider rename branch "master" to "main"

### ISSUE THREAD

**Issue by donhuvy** [moqui/moqui-framework#466]
I see this repository use `master` branch. GitHub tend/prefer use `main` more than `master`. Let's consider rename branch `master` to branch `main` .

> Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from **master**. GitHub is gradually renaming the default branch of our own repositories from master to **main**.

Source: https://github.com/github/renaming

**Comment by jonesde** [comment]
Why?

**Comment by donhuvy** [comment]
I update the content to avoid confusing. Changing main branch's name is not mandatory, even it is not important. It is just a common convention these days.

**Comment by jonesde** [comment]
This is not a common convention as you state, it is a change based on a political and cultural issues. This is not an inexpensive change to make across the roughly two dozen repositories in the moqui organization, and all forks of these repositories including many that are private and/or not hosted on GitHub (it is a common practice to use private forks with private changes).

There is no way of knowing how much this would cost for users of Moqui because there is no way of knowing how many users there are (it is not required that moqui users disclose their use), nor how many dependencies each moqui user has on the primary branch name. As I rough guess I think community wide this could be anywhere from tens of thousands of US Dollars if everything is done well (assuming proper management and communication), and potentially hundreds of thousands of US Dollars if not managed well and production systems are impacted by changes to build and deployment scripts and configuration files.

This is not a decision that I, or any individual involved with Moqui, could make on their own as it impacts a large number of other people. I personally prefer to avoid doing things that harm others.

My personal opinion does not matter. I am only a steward of Moqui, not some sort of owner. If you, or anyone else who finds this issue, believes it is important then there are two venues for discussion that are better than an issue on GitHub:

1. if you want to discuss if publicly, perhaps to better understand the impact and effort involved, then the public mailing list (moqui@googlegroups.com) has the largest audience
2. if you feel this should be demanded, the proper place to make demands is the Moqui Board's private mailing list (moqui-board@googlegroups.com)

For more information please see:

https://moqui.org/m/docs/moqui/Community+Guide#comments-and-discussions

I should note that there is no central legal entity that owns or operates Moqui. Part of the decentralized strategy for Moqui is that there is no legal entity that can be compromised financially or legally to threaten the software itself. In other words, the worst case scenario for any sort of issue with Moqui is simply shutting down the project.

There isn't much to lose other than a little marketing and infrastructure built around the name. The cost to users of Moqui of shutting down Moqui and using the unencumbered source to start a new project under a new name and different infrastructure would be only somewhat larger than the cost of switching the name of the primary branch in all repositories from 'master' to 'main' (ie point to different repo URLs vs same URL except the branch name).

I am not saying this is what I propose or would necessarily support (and of course this could not be my decision alone anyway). I bring this up to clarify the nature of Moqui and hopefully mitigate concerns around this issue. I knew would this come up sooner or later, and have had a few private discussions with different users of Moqui on the topic, including worst case scenario planning.
