### ISSUE TITLE
moqui-elasticsearch still references jcenter

### ISSUE THREAD

**Issue by eigood** [moqui/moqui-framework#470]
https://github.com/moqui/moqui-elasticsearch/blob/1e2a298fdcc28e255a0f0e018b170819b5453d8d/build.gradle#L37

**Comment by jonesde** [comment]
That repository is deprecated (see README.md), to clarify further I have archived the repository on GitHub.

**Comment by eigood** [comment]
If that's the case, then what should happen with database restores that
contain references to it?  What is needed to automatically purge such
data?  I see references in service_job, for instance.

**Comment by jonesde** [comment]
I suppose to automatically purge the first thing needed would some sort of code to automate it. Manual purge is probably easier. Either way the first thing to look at is the data that got into your database from the moqui-elasticsearch component, the most recent version of that is here (and has been the same for a long time):

https://github.com/moqui/moqui-elasticsearch/blob/master/data/ElasticSearchSetupData.xml

In this case you don't really want to purge these, the ServiceJob records still work fine with newer versions of the framework. If you're running an older version of the framework that still supports moqui-elasticsearch (ie moqui-framework 2.1.3) then the original question is a bit different because all repos in that release series used jcenter.
