### ISSUE TITLE
error in connecting to mysql

### ISSUE THREAD

**Issue by amghha** [moqui/moqui-framework#472]
when I set connection in conf file and load the source I get this error:

ERROR         main .moqui.i.e.EntityDatasourceFactoryImpl Error connecting to DataSource transactional (mysql), try 3 of 5: java.lang.ClassNotFoundException: Class [com.mysql.jdbc.jdbc2.optional.MysqlXADataSource] not found

my config is:

<default-property name="entity_ds_db_conf" value="mysql"/>
    <default-property name="entity_ds_user" value="root"/>
    <default-property name="entity_ds_password" value="----"/>
    <default-property name="entity_ds_host" value="localhost"/>
    <default-property name="entity_ds_port" value="3306"/>
    <default-property name="entity_ds_database" value="moqui"/>
    <default-property name="entity_add_missing_startup" value="true"/>

**Comment by jonesde** [comment]
It looks like you are missing the JDBC driver for MySQL. This jar is not included in Moqui by default to avoid bloat and because of the GPL license that could cause redistribution issues for Moqui Framework because Moqui is far more leniently licensed. See:

https://downloads.mysql.com/docs/licenses/connector-j-8.0-gpl-en.pdf
