### ISSUE TITLE
Entity editor number fields are truncated at 3 decimal points

### ISSUE THREAD

**Issue by eigood** [moqui/moqui-framework#501]
I'm trying to edit a product price entity; the popc screen truncates at less decimal points, so I tried to use the low-level entity editor.  The textual input field shows ".008", while the json at the end of the page shows ".008333".  It would be nice if the low-level editor would display and allow updating of values to the same resolution as supported by the underlying database.

**Comment by jonesde** [comment]
This has bothered me for a while as well... the default number formatter from Apache Commons Validator does that 3 decimal limit and it is not a great default. I recently changed a bunch of fields on the EditProduct.xml screen to show more decimal digits (up to the 6 in the DB), but that is an ugly solution to a problem caused by a default limit that doesn't make sense. This commit improves the default number formatter when no format string is specified (including the auto screens/forms): 408380feb03967cad2aa1b23150f8e78ca7df2a5
