### ISSUE TITLE
Long time no release

### ISSUE THREAD

**Issue by amirmf** [moqui/moqui-framework#517]
Hi, Hope you're doing great.
I couldn't find any roadmap for Moqui's releases.
As it seems latest version was released  2 years ago. is there gonna be a new version any time soon ? if yes, giving an estimated release date will help my decision about using framework.
Thanks for your great job,

**Comment by aabiabdallah** [comment]
Hi Amir,The reason why you could not find a roadmap is because one does not exist. New developments and features are mainly community driven. Each of contributors may have his/her own roadmap but these have not been made public as far as I'm aware.If your decision to use the Moqui Framework rests solely on that, then you may not find what you're looking for. However, if you want to know if this project is active and maintained then you can take a look at the commit history and you'll find your answer.Regards,Ayman Abi Abdallah
-------- Original message --------From: Amir Mansouri ***@***.***> Date: 3/4/22  4:04 AM  (GMT-06:00) To: moqui/moqui-framework ***@***.***> Cc: Subscribed ***@***.***> Subject: [moqui/moqui-framework] Long time no release (Issue #517) 
Hi, Hope you're doing great.
I couldn't find any roadmap for Moqui's releases.
As it seems latest version was released  2 years ago. is there gonna be a new version any time soon ? if yes, giving an estimated release date will help my decision about using framework.
Thanks for your great job,
