### ISSUE TITLE
The entities cannot be created in data source nontransactional, configuration, analytical.

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#59]
I use postgres and set up only one transactional data source but only the entities in transactional are created none entities defined  nontransactional, configuration, analytical be created.

**Comment by zhangwei1979** [comment]
If I set up the data sources for nontransactional, configuration, analytical, some seed data cannot be loaded and a  FOREIGN KEY VIOLATION exception is thrown. 

I think the 2 issues above are caused by https://github.com/moqui/moqui-framework/commit/c13c890915e6bad6b070c854cdaaac812c120ba1

**Comment by jonesde** [comment]
Thank you for the report, I hadn't tested this yet with a database that requires creating all tables in advance like Postgres (i.e. where creating tables on the fly in the middle of transactions doesn't work). While various entities are now in different groups there are a few things that still need to be implemented, and even view-entity and possibly code changes needed, to fully support putting these entities in different groups in different databases.

The goal in general with Moqui is for the master branch to always stay in a fully working state, even between releases, so I'll get this fixed ASAP so that it can run in the same setup as before (most entities in the same DB).

**Comment by chunlinyao** [comment]
Maybe related to this line https://github.com/moqui/moqui-framework/blob/master/framework/src/main/groovy/org/moqui/impl/entity/EntityFacadeImpl.groovy#L172

**Comment by chunlinyao** [comment]
@zhangwei1979  Would you like to confirm if it is fixed in 3219ae1

**Comment by zhangwei1979** [comment]
@chunlinyao It works! Thanks for your quick fix.

**Comment by jonesde** [comment]
Thanks Yao, looks good.
