### ISSUE TITLE
Field focus lost when using keyboard to pick in dropdown (in modal)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#85]
This occurs in dialog, opened as modal (dialog).

After I fill the value in the first dropdown using keyboard (search party, then hit Enter to confirm the selection), the field focus is lost (I would expect the focus to jump to the next field on the dialog). But when I hit TAB, the fields on the parent form are focused instead (starting with icon as seen on the screenshot).

If I want to get back on the next field in the dialog, I have to TAB over all items on the parent. This makes use of keyboard quite ineffective.

Can I set the tab index of the fields somehow?

![image](https://cloud.githubusercontent.com/assets/14863763/17289240/17328978-57d9-11e6-809c-04780edc723e.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17288997/f65f489a-57d7-11e6-8de3-5807f19b5492.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17289060/341d6342-57d8-11e6-86af-a1c0d2ff3f89.png)

**Comment by jonesde** [comment]
This can likely be improved, but is an HTML and JavaScript issue so would be in moqui-runtime and not in moqui-framework (the framework itself knows as little as possible about HTML and JavaScript output so that it can be changed without modifying the framework). Please open this issue in the moqui-runtime repository.
