### ISSUE TITLE
Concurrency for dbresource

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#96]
When I create product content in dbresouces://mantle/product/{productId}/... with multiple threads at same time (web client calls aps at same time) it will create two branches for mantle/product with different nodes. Semantically there should be only one path for /mantle/product.

When searching for dbrerouces://mantle/product/... resource facade find root node for "mantle" whose parent is null, but there are two record in dbresources table. 

![image](https://cloud.githubusercontent.com/assets/4743845/18043748/71e93950-6dfc-11e6-8652-ec2952865e9b.png)

Ocassionly I get below exeption
```
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "DB_RES_PAR_FN ON PUBLIC.DB_RESOURCE(PARENT_RESOURCE_ID, FILENAME) VALUES ('100004', 'ZC_AgentPurchaseInvoice_1', 103)"; SQL statement:
INSERT INTO DB_RESOURCE (RESOURCE_ID, PARENT_RESOURCE_ID, FILENAME, IS_FILE, LAST_UPDATED_STAMP) VALUES (?, ?, ?, ?, ?) [23505-192]
```
client is saving two product content with same prefix "dbresources://mantle/product/ZC_AgentPurchaseInvoice_1". Since they are running in different tranaction,  each transaction find no "/mantle/product/ZC_AgentPurchaseInvoice_1" has been created, so both they will create node for "ZC_AgentPurchaseInvoice_1", then first one succeed, the second one fails due to unique index constraint on (parentResourceId, filename).  

Is there a way to avoid such duplication creation of node in dbreource and possible collision in concurrent transactions

**Comment by jonesde** [comment]
There may be a way to avoid this... a little tricky since creating a new record won't lock anything we can try to lock but we can lock the parent DbResource and query again for a match before creating. I made some changes in commit #9387c53 that may fix this.

I did some basic tests on this, and there was a lot of room for improvement in the current code (was extremely basic, didn't do much validation and such), but I don't have easy exhaustive tests so there may still be issues.

**Comment by shendepu** [comment]
It should lock DBResource instead of DBResouceFile https://github.com/moqui/moqui-framework/pull/98

And there is one more case that can't be locked by this code. If the root does not exist, it will be created twice by two concurrent transaction. 

e.g. when creating dbresources://mantle/content/product/{productId_1}, dbresources://mantle/content/product/{productId_2} , but there is no mantle root resource in db yet, there these two creation will create two mantle root resource. 

To solve this, it will need an external lock like "ServiceParameterSemaphore". or currently can be solved by adding mantle root resource in setup data.

**Comment by jonesde** [comment]
Good point, I like the approach of creating the mantle/content path in seed data. I'll add it to the MantleSetupData.xml file.

**Comment by jonesde** [comment]
That is now done in commit #19c9a9e in mantle-usl.

**Comment by chunlinyao** [comment]
I am thinking about the root cause of this issue. It maybe because unique index not work when field  conatins null value. Is there other nullable multi fields unique index in moqui? Will this unique key fix these problems?

    CREATE UNIQUE INDEX test
    ON public.db_resource (COALESCE(parent_resource_id, '-1') , filename );

**Comment by shendepu** [comment]
@chunlinyao It is not parent_resource_id contains null value. It is rather the record of parent resource does not exist when two transactions check it before insert child resource. Both transactions think parent resource does not exist, then both insert same parent resource (its parent resource and filename is same), then violates unique index constraint.

**Comment by chunlinyao** [comment]
If it violates unique index constraint, it will not create two branches. Define unique index with `COALESCE` will prevent create two branches, but one transaction will throw exception.

**Comment by jonesde** [comment]
The idea of the changes I did was to lock the parent record when before creating a child (directory entry), and also re-query for the child after getting a lock on the parent to handle it cleanly when another thread was working on creating the child, i.e. so it waits instead of throwing an exception because of the unique index constraint violation.

The current unique index seems to be working find, even without a default value for the parentResourceId that the COALESCE function would provide. That's a great idea if the issue does ever arise where we need a unique index and allow a field to be null.

**Comment by chunlinyao** [comment]
> That's a great idea if the issue does ever arise where we need a unique index and allow a field to be null.

Yes, when we encapsulated the creation action of the entity like `DBResource` we can use the clean lock based approach, If other framework users will create the entity directly in their services, it's best to prevent duplicate creation in db constraint level.
